language: csharp
solution: SimCivil.sln
dotnet: 2.2.0
dist: trusty
matrix:
  include:
    - mono: latest
  allow_failures:
      mono: none
      env: DOTNETCORE=1
install:
  - nuget restore SimCivil.sln
  - nuget install xunit.runner.console -OutputDirectory testrunner
script:
   - bash ./xunit.bash 
notifications:
    slack: tpdt:fmYoCUlHFzbEE9YxZctMJjJl
